//
// Generated file, do not edit! Created by nedtool 5.4 from SimpleMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SIMPLEMESSAGE_M_H
#define __SIMPLEMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "MyPair.h"
// }}

/**
 * Class generated from <tt>SimpleMessage.msg:26</tt> by nedtool.
 * <pre>
 * message SimpleMessage
 * {
 *     MyPair pairs[];
 *     string names[];
 * }
 * </pre>
 */
class SimpleMessage : public ::omnetpp::cMessage
{
  protected:
    MyPair *pairs; // array ptr
    unsigned int pairs_arraysize;
    ::omnetpp::opp_string *names; // array ptr
    unsigned int names_arraysize;

  private:
    void copy(const SimpleMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SimpleMessage&);

  public:
    SimpleMessage(const char *name=nullptr, short kind=0);
    SimpleMessage(const SimpleMessage& other);
    virtual ~SimpleMessage();
    SimpleMessage& operator=(const SimpleMessage& other);
    virtual SimpleMessage *dup() const override {return new SimpleMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setPairsArraySize(unsigned int size);
    virtual unsigned int getPairsArraySize() const;
    virtual MyPair& getPairs(unsigned int k);
    virtual const MyPair& getPairs(unsigned int k) const {return const_cast<SimpleMessage*>(this)->getPairs(k);}
    virtual void setPairs(unsigned int k, const MyPair& pairs);
    virtual void setNamesArraySize(unsigned int size);
    virtual unsigned int getNamesArraySize() const;
    virtual const char * getNames(unsigned int k) const;
    virtual void setNames(unsigned int k, const char * names);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SimpleMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SimpleMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIMPLEMESSAGE_M_H

